version: '3'

services:

  spring-cache-redis:
    image: habeebcycle/spring-cache-redis:v1
    container_name: spring-cache-redis-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/spring_mongo
      - SPRING_CACHE_REDIS_TIME-TO-LIVE=60s
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis

  # $ mongo
  mongodb:
    image: mongo:3.6.9
    container_name: mongo-database
    ports:
      - "27017:27017"
    command: mongod --smallfiles

  # $ redis
  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: redis-cli -h redis
